#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT="${CARTHINGY_PORT:-8787}"

log() { printf '[carthingy] %s\n' "$*"; }
fail() { printf '[carthingy] ERROR: %s\n' "$*" >&2; exit 1; }

detect_adb() {
  if [[ -n "${CAR_THING_ADB:-}" ]]; then
    command -v "$CAR_THING_ADB" >/dev/null 2>&1 || fail "CAR_THING_ADB=$CAR_THING_ADB is not runnable"
    printf '%s' "$CAR_THING_ADB"
    return
  fi
  command -v adb >/dev/null 2>&1 || fail "adb not found. Run: brew install --cask android-platform-tools"
  command -v adb
}

detect_serial() {
  local adb_bin="$1"
  local lines count
  lines="$("$adb_bin" devices 2>/dev/null | tail -n +2 | tr -d '\r' | awk '$2=="device" {print $1}')"
  count=0
  if [[ -n "$lines" ]]; then count="$(printf '%s\n' "$lines" | grep -c . || true)"; fi
  case "$count" in
    1) printf '%s' "$lines" ;;
    0) fail "No Car Thing on adb. See README for one-time firmware setup." ;;
    *) fail "Multiple adb devices attached. Set CAR_THING_SERIAL to pick one." ;;
  esac
}

detect_node() {
  if [[ -n "${CARTHINGY_NODE:-}" ]]; then
    [[ -x "$CARTHINGY_NODE" ]] || fail "CARTHINGY_NODE=$CARTHINGY_NODE is not runnable"
    printf '%s' "$CARTHINGY_NODE"
    return
  fi
  if command -v node >/dev/null 2>&1; then
    command -v node
    return
  fi
  if [[ -x /opt/homebrew/bin/node ]]; then
    printf '%s' /opt/homebrew/bin/node
    return
  fi
  fail "Node.js 20+ required. Install from https://nodejs.org or: brew install node"
}

ensure_node() {
  local node_bin="$1"
  [[ -x "$node_bin" ]] || fail "Node.js 20+ required. Install from https://nodejs.org or: brew install node"
  local major
  major="$("$node_bin" -p "process.versions.node.split('.')[0]")"
  if (( major < 20 )); then
    fail "Node.js 20+ required (found $("$node_bin" --version))"
  fi
}

check_credentials() {
  local creds="$HOME/.claude/.credentials.json"
  if [[ -n "${CLAUDE_CONFIG_DIR:-}" ]]; then
    creds="${CLAUDE_CONFIG_DIR}/.credentials.json"
  fi
  if [[ -f "$creds" ]]; then
    return 0
  fi
  if [[ "$(uname -s)" == "Darwin" ]] && {
    /usr/bin/security find-generic-password -s "Claude Code-credentials" -a "$(id -un)" >/dev/null 2>&1 \
      || /usr/bin/security find-generic-password -s "Claude Code-credentials" >/dev/null 2>&1
  }; then
    return 0
  fi
  log "No Claude credentials yet at $creds"
  if [[ "$(uname -s)" == "Darwin" ]]; then
    log "On macOS, Claude Code keeps the token in Keychain (Claude Code-credentials), not that file."
  fi
  log "Install Claude Code and run \`claude\` to sign in before usage data will load."
  return 1
}

install_adb_macos() {
  if command -v adb >/dev/null 2>&1; then
    return
  fi
  if [[ "$(uname -s)" != "Darwin" ]]; then
    return
  fi
  if command -v brew >/dev/null 2>&1; then
    log "Installing android-platform-tools via Homebrew…"
    brew install --cask android-platform-tools
  fi
}

write_config() {
  local adb_bin="$1"
  local serial="$2"
  local node_bin="$3"
  local config="$REPO_ROOT/carthingy.conf"
  if [[ -f "$config" ]]; then
    log "Config exists at $config (not overwriting)"
    if ! grep -q '^CARTHINGY_NODE=' "$config"; then
      printf '\nCARTHINGY_NODE=%s\n' "$node_bin" >> "$config"
      log "Pinned CARTHINGY_NODE=$node_bin"
    fi
    return
  fi
  cat > "$config" <<EOF
# Generated by scripts/setup.sh
CAR_THING_ADB=$adb_bin
CAR_THING_SERIAL=$serial
CARTHINGY_NODE=$node_bin
CARTHINGY_PORT=$PORT

# Set these to your radar origin. Do not commit this file.
OFFICE_LAT=
OFFICE_LON=
OFFICE_RADIUS_NM=7
OFFICE_LABEL="Office"

# Preset 1-4 hotkeys. Format: Label|open args
HOTKEY_1="Calendar|open -a Calendar"
HOTKEY_2="Mail|open -a Mail"
HOTKEY_3="Slack|open -a Slack"
HOTKEY_4="Safari|open -a Safari"
EOF
  log "Wrote $config"
}

main() {
  log "Car Thingy setup"
  install_adb_macos
  local node_bin
  node_bin="$(detect_node)"
  ensure_node "$node_bin"
  check_credentials || true

  local adb_bin serial
  adb_bin="$(detect_adb)"
  serial="$(detect_serial "$adb_bin")"

  log "adb: $adb_bin"
  log "node: $node_bin"
  log "device: $serial"

  write_config "$adb_bin" "$serial" "$node_bin"
  bash "$REPO_ROOT/scripts/apply-kiosk.sh"

  log ""
  log "Setup complete. Start the dashboard with:"
  log "  ./scripts/start.sh"
  log ""
  log "Preview in your browser at http://127.0.0.1:${PORT}/ while start.sh is running."
}

main "$@"
